blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^post/(?P<blog_id>[0-9]+)/$', views.detail, name='blog_detail'),
	url(r'^category/(?P<category_id>[0-9]+)/$', views.category_index, name='category_index'),
]

excelerate/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
    url(r'^mailing/', include('mailing.urls')),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root', settings.STATIC_ROOT}),
]

mailing/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^activate/$', views.activate, name='activation'),
	url(r'^cancel/$', views.cancel, name='cancellation'),
]

blog/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

# Create your models here.

class Post(models.Model):
	title = models.CharField(max_length=500, unique=True)
	title_slug = models.SlugField(max_length=500, unique=True)
	publication_date = models.DateTimeField('date created', auto_now_add=True)
	published = models.BooleanField(default=False, blank=False)
	content = models.TextField()

	author = models.ForeignKey(User, default=None)
	category = models.ForeignKey('blog.Category')

	def __str__(self):
		return '%s' % (self.title)


class Category(models.Model):
	name = models.CharField(max_length=100, unique=True)
	description = models.CharField(max_length=500)

	parent_category = models.ForeignKey('blog.Category', default=None, blank=True, null=True)

	def __str__(self):
		return '%s' % (self.name)

class Comment(models.Model):
	text = models.CharField(max_length=1000)
	creation_date = models.DateTimeField('date created', auto_now_add=True)
	
	parent_post = models.ForeignKey('blog.Post', default=None, blank=False, null=False)
	author = models.ForeignKey(User, default=None, blank=True)

	def __str__(self):
		return '%s' % (self.text)

mailing/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from datetime import datetime

import hashlib

# Create your models here.

class Registration(models.Model):
	email = models.EmailField(max_length=500, unique=True)
	email_hash = models.CharField(max_length=500, unique=False, blank=True, null=True, editable=False)
	registration_date = models.DateTimeField('Registration date', auto_now_add=True, blank=False)
	cancellation_date = models.DateTimeField('Cancellation date', default=None, blank=True, null=True)
	activation_date = models.DateTimeField('Activation date', default=None, blank=True, null=True)
	active = models.BooleanField(default=True, blank=False)
	user = models.ForeignKey(User, default=None, null=True, blank=True)

	def __str__(self):
		activestr = "Active"
		if not self.active : activestr = "Disabled"
		return self.email + " (" + activestr + ")"

	def save(self, *args, **kwargs):
		self.email_hash = hashlib.sha1(self.email).hexdigest()
		super(Registration, self).save(*args, **kwargs)

	def activate_if_exists(self):
		reg = Registration.objects.get(email=self.email)
		if reg is not None:
			# object already exists, need to set activation to True and resave
			reg.active = True
			reg.activation_date = datetime.now()
			reg.save()
			return True

		return False


	def disable(self):
		self.active = False
		self.cancellation_date = datetime.now()
		self.save()
		return True

mailing/forms.py
from django import forms

class ActivateEmailForm(forms.Form):
	email = forms.EmailField(label='')

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from blog.models import Post

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger



#definition of main views

def detail(request, blog_id):
	p = Post.objects.get(id=blog_id)
	return render(request, 'blog/post_detail.html', {'post':p})

def index(request):
	# set category
	category = request.GET.get('cat')
	print category

	# show top 5 blog posts
	if (category is None):
		posts = Post.objects.filter(published=True).order_by('-publication_date')
	else:
		posts = Post.objects.filter(published=True, category__name=category).order_by('-publication_date')

	# Pagination
	pgtr = Paginator(posts, 2)
	page = request.GET.get('page')


	try:
		posts = pgtr.page(page)
	except PageNotAnInteger:
		posts = pgtr.page(1)
	except EmptyPage:
		posts = pgtr.page(pgtr.num_pages)

	return render(request, 'blog/index.html', {'posts' : posts})


def category_index(request, category_id):
	return render(request, 'blog/test.html')

mailing/views.py
from django.contrib import messages
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .forms import ActivateEmailForm
from .models import Registration
# Create your views here.

def activate(request):
	if request.method == 'POST':
		form = ActivateEmailForm(request.POST)
		if form.is_valid():
			registration = Registration(email=form.cleaned_data['email'], active=True)
			if registration.activate_if_exists():
				messages.info(request, "We have reactivated your account, thanks!")
				#print "HELLO"
				# no further action, reactivated
			else:
				messages.info(request, "You are successfully registered!")
				registration.save()

			# set session so the box is not displayed next time
			request.session['registered_email'] = True
			return HttpResponseRedirect(request.POST.get('next'))
	
	return HttpResponseRedirect('/blog/')


def cancel(request):
	# get the email hash
	email_hash = request.GET.get('h')
	# TODO add a response message
	if email_hash is None:
		return HttpResponseRedirect('/mailing/')		

	try:
		res = Registration.objects.get(email_hash=email_hash)
	except Registration.DoesNotExist:
		# TODO add error message
		messages.error(request, 'Email address does not exist')
		return HttpResponseRedirect('/blog/') 
	except:
		return HttpResponseRedirect('/blog/') 

	res.disable()
	messages.info(request, "You unsubscribed from our mailinglist with email address: %s " % (res.email))
	return HttpResponseRedirect('/blog/')

blog/templates/blog/admin/change_form.html
{% extends "admin/change_form.html" %}

{% load wysiwyg %}

{% block extrahead %}
	
	{{ block.super }}
	
	{% wysiwyg_setup %}
	<script type="text/javascript">
		(function($) {
		    $(document).ready(function() {
		        $('label[for="id_content"]').hide();
		    });
		})(django.jQuery);
	</script>
	
{% endblock %}



{% block extrastyle %}
	
	{{ block.super }}
	
	<style type="text/css">
		<!--
			
			{% comment %}
				
				The below CSS rules are here to fix admin layout issues using 
				CKEditor v3.6.1, or YUI Editor, via Django 1.3.
				
				Note: "kama" is the skin name; you will need to change this if 
				using a different skin.
				
				CSS tested with:
				
				Mac OSX v10.6.7
				Chrome v12.0.742.100; Firefox v5.0; Safari v5.0.5; Opera v11.11
				
				Windows Vista
				Chrome v11.11; Internet Explorer v9.0.8112.16421; 
				Internet Explorer v8.0.6001.19019; Opera v11.11; Safari v5.0.5; 
				Firefox v3.6.11; Flock v3.5.3.4641
				
				Windows XP
				Internet Explorer v6.0.2900.5512...
				
			{% endcomment %}
			
			/* CKEditor: */
			.cke_skin_kama {
				/* Un-comment one line or the other: */
				/*width: 85%; float: left; display: inline;*/
				/*clear: left;*/
			}
			
			/* YUI Editor: */
			.yui-editor-container {
				/* IBID: */
				/*float: left; display: inline;*/
				/*clear: left;*/
			}
			
		-->
	</style>
	
{% endblock %}

{% block content %}
	
	{{ block.super }}
	
	{# Replace XXXXXXXX with field name: #}
	{% wysiwyg_editor "id_content" "id_content_editor" "{ height: 1000, toolbar: 'basic' }"%}
	
	{% comment %}
		{# ckeditor custom config example #}
		{% wysiwyg_editor "id_XXXXXXXX" "id_XXXXXXXX_editor" "{ toolbar: 'compact_toolbar' }" %}
	{% endcomment %}

{% endblock %}

blog/templates/blog/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Excelerate blog{% endblock %}</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/excelerate_overrides.css' %}">

    <!-- Custom CSS -->
    <link href="{% static 'css/blog-home.css' %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/blog/">Excelerate</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Content 
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/blog/?cat=Productivity">Productivity</a></li>
                            <li><a href="/blog/?cat=Functionality">Functionality</a></li>
                            <li><a href="/blog/?cat=Advanced Modeling">Modeling</a></li>
                            <li><a href="/blog/?cat=VBA">VBA</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">About us</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


    <!-- Messages -->
    {% include 'blog/messaging.html' %}


    <!-- Page Content -->
    <div class="container">
        <div class="row">
        
            {% block main_content %}

            {% endblock %}

            {% include 'blog/sidepanel.html' %}


        </div>
        <!-- /.row -->


        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>

</html>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block title %}Excelerate home{% endblock %}

{%block main_content %}

<h2 class="page-header">
    Ecxelerate
    <small>Latest blog posts on Excel</small>
</h2>

<div class="col-md-8">
<!-- First Blog Post -->
{% for post in posts %}
<div class="row">
        <h3>
            <a href="/blog/post/{{post.id}}">{{post.title}}</a>
        </h3>
</div>
<div class="row">
    <p>
        {{ post.content | truncatewords:50 | striptags | safe }} <a href="/blog/post/{{post.id}}">read more</a>
    </p>
</div>
<div class="row">
        <h5 class="text-right color-gray">{{post.publication_date | date:"D j F Y" }}</h5>
</div>
<hr>
{% endfor %}

<!-- Pager -->
<ul class="pager">
    {% if posts.has_previous %} 
    <li class="previous">
        <a href="?page={{ posts.previous_page_number }}">&larr; Newer</a>
    </li>
    {% endif %}
    <li>Page {{ posts.number }} of {{ posts.paginator.num_pages }} </li>
    
    {% if posts.has_next %} 
    <li class="next">
        <a href="?page={{ posts.next_page_number }}">Older &rarr;</a>
    </li>
    {% endif %} 
</ul>
</div>
{% endblock %}

blog/templates/blog/index_template.html
{% extends 'blog/base.html' %}

{% block title %}Excelerate home{% endblock %}

{%block main_content %}

<h4 class="page-header">
    Ecxelerate
    <small>Latest posts on Excel</small>
</h4>

<!-- First Blog Post -->
<h5>
    <a href="#">Blog Post Title</a>
</h5>
<p class="lead">
    by <a href="index.php">Start Bootstrap</a>
</p>
<p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:00 PM</p>
<hr>
<img class="img-responsive" src="http://placehold.it/900x300" alt="">
<hr>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, veritatis, tempora, necessitatibus inventore nisi quam quia repellat ut tempore laborum possimus eum dicta id animi corrupti debitis ipsum officiis rerum.</p>
<a class="btn btn-primary" href="#">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>

<hr>


<!-- Pager -->
<ul class="pager">
    <li class="previous">
        <a href="#">&larr; Older</a>
    </li>
    <li class="next">
        <a href="#">Newer &rarr;</a>
    </li>
</ul>

{% endblock %}

blog/templates/blog/messaging.html
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="row message{% if message.tags %} message-{{ message.tags }}"{% endif %}>
                    
                        {% if message.tags == 'info' or message.tags == 'success' %}
                            <span class="msgglyph glyphicon glyphicon-ok"></span>
                        {% elif message.tags == 'warning' or message.tags == 'debug' %}
                            <span class="msgglyph glyphicon glyphicon-warning-sign"></span>
                        {% elif message.tags == 'error' %}
                            <span class="msgglyph glyphicon glyphicon-remove"></span>
                        {% endif %}

                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    </div>

blog/templates/blog/post_comments.html
<!-- Blog Comments -->

    <!-- Comments Form -->
    <div class="well">
        <h4>Leave a Comment:</h4>
        <form role="form">
            <div class="form-group">
                <textarea class="form-control" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

    <hr>

    <!-- Posted Comments -->

    <!-- Comment -->
    <div class="media">
        <a class="pull-left" href="#">
            <img class="media-object" src="http://placehold.it/64x64" alt="">
        </a>
        <div class="media-body">
            <h4 class="media-heading">Start Bootstrap
                <small>August 25, 2014 at 9:30 PM</small>
            </h4>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
        </div>
    </div>

    <!-- Comment -->
    <div class="media">
        <a class="pull-left" href="#">
            <img class="media-object" src="http://placehold.it/64x64" alt="">
        </a>
        <div class="media-body">
            <h4 class="media-heading">Start Bootstrap
                <small>August 25, 2014 at 9:30 PM</small>
            </h4>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            <!-- Nested Comment -->
            <div class="media">
                <a class="pull-left" href="#">
                    <img class="media-object" src="http://placehold.it/64x64" alt="">
                </a>
                <div class="media-body">
                    <h4 class="media-heading">Nested Start Bootstrap
                        <small>August 25, 2014 at 9:30 PM</small>
                    </h4>
                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                </div>
            </div>
            <!-- End Nested Comment -->
        </div>
    </div>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block title %}Excelerate home - blog detail{% endblock %}

{%block main_content %}

<!-- Blog Post Content Column -->
<div class="col-lg-8">

    <!-- Blog Post -->

    <!-- Title -->
    <h1>{{post.title}}</h1>

    <!-- Author -->
    <p class="lead">
        by <a href="#">{{post.author}}</a>
    </p>

    <hr>

    <!-- Date/Time -->
    <p><span class="glyphicon glyphicon-time"></span> Posted on {{post.publication_date | date:"g:i A, D j F Y" }}</p>

    <hr>

    <!-- Post Content -->
    
    <p>
        {{ post.content | safe }}
    </p>


    <hr>

</div>
{% endblock %}

blog/templates/blog/sidepanel.html
<!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Blog Search Well -->

                {% include 'mailing/registerbox.html' %}
                

                <!-- Blog Categories Well -->
                <!-- <div class="well">
                    <h4>Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                        
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                        
                    </div>
                    
                </div> -->

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>About us</h4>
                    <p>We are a group of Excel enthusiasts. In our professional lives we encounter Excel with all its quirks on a daily basis. Every now and then we run into issues, or we learn something new. To spare you the pain, we'd like to share with you what we find!</p>
                </div>

            </div>

blog/templates/blog/test.html
{% load wysiwyg %}
{% wysiwyg_setup %}

<textarea id="foo"></textarea>

{% wysiwyg_editor "foo" %}

mailing/templates/mailing/registerbox.html
{% if not request.session.registered_email or True %}

<div class="well">
	<h4>Register for our newsletter!</h4>
	<div class="input-group">
		
		<form action="/mailing/activate/" method="post">
		{% csrf_token %}
	    <span class="input-group-btn">
	    <input id="id_email" name="email" type="email" class="form-control"/>
	        <button class="btn btn-default" type="submit" >
	            <span class="glyphicon glyphicon-chevron-right"></span>
	    	</button>
	    <input type="hidden" name="next" value="{% firstof request.path '/' %}" />
	    </span>
		</form>
	
	</div>
<!-- /.input-group -->
</div>

{%  endif %}

mailing/templates/mailing/test.html
{% extends 'blog/base.html' %}

{% block title %}Excelerate home{% endblock %}

{%block main_content %}

<h2 class="page-header">
    Ecxelerate
    <small>Latest posts on Excel</small>
</h2>

<div class="col-md-8">


	<form action="/mailing/activate/" method="post">
	{% csrf_token %}
		
		{{ form }}
		
		<input type="submit" value="ok">

	</form>

</div>
{% endblock %}




<div class="well">
                    <h4>Register for our newsletter!</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                        </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>